### ISSUE TITLE
에러코드를 Enum으로 관리합니다./OAuth2 filter 오류 해결

### ISSUE THREAD

**Issue by jang-namu** [Your-Lie-in-April/server#13]
## 어떤 기능인가요?
여러 곳에서 사용되는 에러코드와 메세지를 Enum으로 한 곳에서 관리합니다.

## 작업 상세 내용

- [ ] 예외별 에러코드 및 메세지 정의
- [ ] Enum으로 대체

**Comment by squidjiny** [comment]
ENUM으로 메시지만 관리할건지, http상태코드와 에러코드(CommonResponseDto의 첫번째 인수) 까지 관리할건지 정해야 할 것 같습니다.

**Comment by jang-namu** [comment]
> ENUM으로 메시지만 관리할건지, http상태코드와 에러코드(CommonResponseDto의 첫번째 인수) 까지 관리할건지 범위를 정해야 할 것 같습니다.
> 
> 그리고 현재 오류를 전부 0으로 분류하고 있는데 세분화 할 생각이 있으신가요??

backlog: 에러코드, 메시지, HTTP응답 세개를 관리합니다.
