### ISSUE TITLE
ExceptionHandling을 담당하는 클래스가 빈처럼 사용되지 않는 것 같습니다!

### ISSUE THREAD

**Issue by jang-namu** [Your-Lie-in-April/server#15]
## 어떤 부분인가요?

SecurityConfig에서 ExceptionHading을 하는 두 개의 클래스가 현재 빈처럼 사용되지 않고,
매 요청마다 객체를 새로 생성하는 것으로 보입니다.

![image](https://github.com/Your-Lie-in-April/server/assets/121238128/36a1cf5a-9a48-4972-99b9-ca01365f02ee)

**Comment by squidjiny** [comment]
왜 찝찝한가 했는데 이부분을 빼먹었네요

예전에 책을 보면서 구현을 할 때 책에서도 저런식으로 구현을 해놔서 의구심 자체가 없었습니다. 

말씀하신 부분에 문제가 생기지 않는지 다시 한번 검토해보도록 하겠습니다

감사합니다.

**Comment by squidjiny** [comment]
@Component에 대해 좀 더 자세히 알아보니까

Bean을 등록해서 Lifecycle을 스프링부트에서 관리하는게 맞는 것 같은데 확실히 문법이 이상하네요...?

이거는 Jwtexceptionhandling 처럼 만드는게 맞는 것 같네요

수정하도록 하겠습니다!(feature/15-exceptionhandling-fix)
