### ISSUE TITLE
도메인을 구현합니다

### ISSUE THREAD

**Issue by jang-namu** [Your-Lie-in-April/server#3]
## 어떤 기능인가요?
도메인을 추출하여 ERD를 작성하고 엔티티 클래스로 구현합니다

## 작업 상세 내용

- [x] ERD 작성
- [x] JPA 관련 의존성 추가
- [x] 엔티티 클래스 추가

**Comment by squidjiny** [comment]
선배님 풀리퀘 날리셨슴까
안보이는디

**Comment by jang-namu** [comment]
> 선배님 풀리퀘 날리셨슴까
> 
> 안보이는디
> 
> 
> 
> 아 찾았다 ㅈㅅ

풀리퀘는 기능개발이 끝나고 로컬에서 테스트가 완료된 상태에서 올립니다
